pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Rbd-Antoine/PrestaBanco']])
                dir("PrestaBank-Frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("PrestaBank-Frontend"){
                    script{
                         withCredentials(credentialsId: 'docker-credentials'){
                            script {
                                if (isUnix()) {
                                    sh 'docker build -t rbdantoine/frontend-image:latest PrestaBank-Frontend'
                                } else {
                                    bat 'docker build -t rbdantoine/frontend-image:latest PrestaBank-Frontend'
                                }
                            }
                            script {
                                if (isUnix()) {
                                    sh 'docker push rbdantoine/frontend-image:latest'
                                } else {
                                    bat 'docker push rbdantoine/frontend-image:latest'
                                }
                            }
                        }
                    }                    
                }
            }
        }
    }
}

