pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Rbd-Antoine/PrestaBanco']])
                dir("PrestaBank-Frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("gestion-estudiantes-frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t rbdantoine/frontend-image:latest PrestaBank-frontend"
                            bat "docker push rbdantoine/frontend-image:latest"
                        }
                    }                    
                }
            }
        }
    }
}

