pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Rbd-Antoine/PrestaBanco']])
                dir("PrestaBank-Frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage('Push frontend') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'docker build --no-cache -t rbdantoine/frontend-image:latest .'
                    } else {
                        bat 'docker build --no-cache -t rbdantoine/frontend-image:latest .'
                    }
                }

                withCredentials([string(credentialsId: 'dockerhubpassword', variable: 'dockerpw')]) {
                    script {
                        if (isUnix()) {
                            sh 'docker login -u rbdantoine -p ${dockerpw}'
                        } else {
                            bat 'docker login -u rbdantoine -p %dockerpw%'
                        }
                    }
                }
                script {
                    if (isUnix()) {
                        sh 'docker push rbdantoine/frontend-image:latest'
                    } else {
                        bat 'docker push rbdantoine/frontend-image:latest'
                    }
                }
            }
        }
    }
}