services:
  # Database service
  mysql:
    image: mysql:latest
    container_name: mysql-prestabancodb
    environment:
      MYSQL_DATABASE: evaluacion1_db
      MYSQL_USER: username
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  # Frontend services
  frontend1:
    image: rbdantoine/frontend-image:latest
    networks:
      - frontend-network

  frontend2:
    image: rbdantoine/frontend-image:latest
    networks:
      - frontend-network

  frontend3:
    image: rbdantoine/frontend-image:latest
    networks:
      - frontend-network

  # backtend services
  backend1:
    image: rbdantoine/backend-image:latest
    environment:
      DB_HOST: mysql-prestabancodb
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: admin
      DB_NAME: evaluacion1_db
    depends_on:
      - mysql
    networks:
      - backend-network

  backend2:
    image: rbdantoine/backend-image:latest
    environment:
      DB_HOST: mysql-prestabancodb
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: admin
      DB_NAME: evaluacion1_db
    depends_on:
      - mysql
    networks:
      - backend-network

  backend3:
    image: rbdantoine/backend-image:latest
    environment:
      DB_HOST: mysql-prestabancodb
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: admin
      DB_NAME: evaluacion1_db
    depends_on:
      - mysql
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backtend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  mysql-data:
